version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - mongo-network
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/task-manager?authSource=admin
      ME_CONFIG_BASICAUTH: false
    networks:
      - mongo-network

  server:
    build:
      context: ./backend
    container_name: server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://root:root@mongo:27017/task-manager?authSource=admin
      - PORT=5000
    networks:
      - mongo-network
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  mongo-data:
    driver: local

networks:
  mongo-network:
    driver: bridge
