version: "3.8"

services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root # Changed to match your .env
      - MONGO_INITDB_DATABASE=task-manager # Changed to match your .env
    networks:
      - mongo-network
    volumes:
      - mongo-data:/data/db

  app: # Changed from mongo-express to app
    build:
      context: .
    container_name: server
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb://root:root@mongo:27017/task-manager?authSource=admin
      - PORT=5000
    networks:
      - mongo-network
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - ./:/app # Only if you need hot-reload during development
      - /app/node_modules

volumes:
  mongo-data:
    driver: local

networks:
  mongo-network:
    driver: bridge